- constructorio-client/src/main/java/com/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/com/constructor/client/ConstructorItem.java
- constructorio-client/src/test/java/com/constructor/client/ConstructorTest.java
- Added batchRemove
- Cleaned up test cases
- Cleaned up method signatures to be more consistent
- Methods taking in `String...` as argument have been changed to take in `String[]` instead
> Java client updates

- constructorio-client/pom.xml
- constructorio-client/src/main/java/io/constructor/client/AutocompleteResponse.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOTest.java
* Add Mockito and Maven-Model to dependencies
* Add new getVersionParamString method
* Add version to autocomplete requests
> [CH 2712] Add Client Version to Requests

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/UserInfo.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOTest.java
- constructorio-client/src/test/java/io/constructor/client/UserInfoTest.java
* Add new serializeUserInfo method
* Add new UserInfo Class (contains clientId and sessionId)
* Add new UserInfoTest class
> [CH 2713] Client/Session ID

- constructorio-client/pom.xml
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorIOHttpInterceptor.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOTest.java
> Swap out Unirest for OkHttp3

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/NaturalLanguageSearchRequest.java
- constructorio-client/src/main/java/io/constructor/client/VoiceSearchRequest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchTest.java
- constructorio-client/src/test/java/io/constructor/client/NaturalLanguageSearchRequestTest.java
- constructorio-client/src/test/java/io/constructor/client/SearchRequestTest.java
* Add new voiceSearch and voiceSearchAsJSON methods
* Add new VoiceSearchRequest model
* Add tests
> [CH 3497] Voice Search

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/RecommendationsRequest.java
- constructorio-client/src/main/java/io/constructor/client/models/RecommendationsResponse.java
- constructorio-client/src/main/java/io/constructor/client/models/RecommendationsResponseInner.java
- constructorio-client/src/main/java/io/constructor/client/models/ResultPod.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIORecommendationsTest.java
- constructorio-client/src/test/java/io/constructor/client/RecommendationsRequestTest.java
- constructorio-client/src/test/resources/response.recommendations.home_page_1.json
Implements method to retrieve recommendations from C.IO endpoint.
+ Tests
+ Response model
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running io.constructor.client.ConstructorIOBasicTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.903 sec
Running io.constructor.client.ModelsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running io.constructor.client.ConstructorItemTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running io.constructor.client.SearchRequestTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running io.constructor.client.ConstructorIOSearchTest
Tests run: 12, Failures: 0, Errors: 0, …
```
> [CH9786] Implement recommendation methods

- constructorio-client/src/main/java/io/constructor/client/BrowseRequest.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/SearchRequest.java
- constructorio-client/src/main/java/io/constructor/client/models/BrowseResponse.java
- constructorio-client/src/main/java/io/constructor/client/models/BrowseResponseInner.java
- constructorio-client/src/main/java/io/constructor/client/models/FilterFacet.java
- constructorio-client/src/main/java/io/constructor/client/models/FilterFacetOption.java
- constructorio-client/src/main/java/io/constructor/client/models/FilterGroup.java
- constructorio-client/src/main/java/io/constructor/client/models/Result.java
- constructorio-client/src/main/java/io/constructor/client/models/SearchResponseInner.java
- constructorio-client/src/test/java/io/constructor/client/BrowseRequestTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBrowseTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIONaturalLanguageSearchTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchTest.java
- constructorio-client/src/test/java/io/constructor/client/ModelsTest.java
- constructorio-client/src/test/java/io/constructor/client/SearchRequestTest.java
- constructorio-client/src/test/resources/response.browse.color.blue.json
> Enable Browse Requests + Collections

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOAutocompleteTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBasicTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBrowseTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIORecommendationsTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchTest.java
> [CH10267] Add ability to set apiKey after instance has been defined (setter)

- constructorio-client/pom.xml
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
```
Tests run: 113, Failures: 0, Errors: 0, Skipped: 0
```
> Improve string check for sortBy.

- constructorio-client/pom.xml
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/OkHttpUrlBuilderUtils.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOAutocompleteUrlEncodingTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBasicTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBrowseTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchUrlEncodingTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchUrlTest.java
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/
> CH10224 : Encoding tests

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/UserInfo.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOBasicTest.java
- constructorio-client/src/test/java/io/constructor/client/UserInfoTest.java
> Add ability to set User-Agent header on userInfo object + tests.

- README.md
* I noticed that we don't currently support filters for the recommendations, so I didn't update the README to reflect that.
Not sure why I can't tag `integration-engineers` as a reviewer 🤔
> [CSL 195] Update README w/ Browse and Recs

- README.md
- constructorio-client/src/main/java/io/constructor/client/CatalogRequest.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/test/java/io/constructor/client/CatalogRequestTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOCatalogTest.java
- constructorio-client/src/test/resources/csv/item_groups.csv
- constructorio-client/src/test/resources/csv/items.csv
- constructorio-client/src/test/resources/csv/variations.csv
* Add support for the catalog endpoint (replace, update)
* Update README
* Not sure what's the best way to structure the code (i.e. pass as argument or just use a setter). Please let me know if I should make any adjustments. Thanks!
> [CSL 196] Add Catalog Endpoint Support

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOCatalogTest.java
@jjl014 Not sure how to test what you mentioned, looked at the tests in node and they seem to just be a repeat of updateCatalog as well. If you would like to take over adding a test for it that would be cool. I don't think there is a good way to test it but I could be wrong.
> [CSL-1073] Add patchCatalog method

- constructorio-client/pom.xml
Tests pass except for the same ones that fail on master.
> [CSL-1380] Update gson version

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorItem.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorVariation.java
- constructorio-client/src/main/java/io/constructor/client/ItemsRequest.java
- constructorio-client/src/main/java/io/constructor/client/VariationsRequest.java
- constructorio-client/src/main/java/io/constructor/client/models/ItemsResponse.java
- constructorio-client/src/main/java/io/constructor/client/models/VariationsResponse.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOCatalogTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOItemsTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOVariationsTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorItemTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorVariationTest.java
- constructorio-client/src/test/java/io/constructor/client/Utils.java
This is ready for review but marked as do not merge because GET tests are failing due to c parameter. The backend is working on the change to make c a valid parameter, after that's done, the tests should be passing.
> [CSL-1485] Implement missing items V2 endpoint

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/RecommendationsRequest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIORecommendationsTest.java
- constructorio-client/src/test/java/io/constructor/client/RecommendationsRequestTest.java
* Add support for filters in recs
* All tests pass 👍
> [CSL 1616] Add support for filters in Recommendations

- constructorio-client/src/main/java/io/constructor/client/AllTasksRequest.java
- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/TaskRequest.java
- constructorio-client/src/test/java/io/constructor/client/AllTasksRequestTest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOTasksTest.java
Adjusted test for start and end date to use last 30 days instead of hard coded date.
> [CSL-1763] Add support for type in tasks

- constructorio-client/pom.xml
> [CSL-2926] Update dependency

- constructorio-client/src/main/java/io/constructor/client/models/FilterFacetOption.java
Removes validation logic from setter.
> [CI-3537] Remove setter logic

- constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
- constructorio-client/src/main/java/io/constructor/client/SearchRequest.java
- constructorio-client/src/test/java/io/constructor/client/ConstructorIOSearchTest.java
- constructorio-client/src/test/java/io/constructor/client/SearchRequestTest.java
`ConstructorIO`
- `SearchRequest`
- `SearchRequestTest`
- `ConstructorIOSearchTest`
> Search support for filter_match_type
